#pragma once

#include <ppb/ppb.hpp>

// Generated by protoc-gen-ppb --emit-wkt-bundle. DO NOT EDIT.
// protobuf runtime: 7.35.0
//
// Fused schemas for the supported well-known types. none, lean, and full
// are identical for these six files (the only repeated field,
// FieldMask.paths, is a never-packed string), so one header serves all modes.

// clang-format off
namespace ppb_gen::google::protobuf::Any
{
    enum class F : ::std::int32_t
    {
        type_url = 1,
        value = 2,
    };

    constexpr ::std::size_t max_depth = 0;

    using schema = ::ppb::auto_schema<
        // ppb::on<F::type_url>(...)
        ::ppb::proto3_utf8string<F::type_url>,
        // ppb::on<F::value>(...)
        ::ppb::proto3_bytes<F::value>>;

    using merge_schema = ::ppb::auto_schema<
        // ppb::on<F::type_url>(...)
        ::ppb::utf8string<F::type_url>,
        // ppb::on<F::value>(...)
        ::ppb::bytes<F::value>>;
}

namespace ppb_gen::google::protobuf::Duration
{
    enum class F : ::std::int32_t
    {
        seconds = 1,
        nanos = 2,
    };

    constexpr ::std::size_t max_depth = 0;

    using schema = ::ppb::auto_schema<
        // ppb::on<F::seconds>(...)
        ::ppb::proto3_int64<F::seconds>,
        // ppb::on<F::nanos>(...)
        ::ppb::proto3_int32<F::nanos>>;

    using merge_schema = ::ppb::auto_schema<
        // ppb::on<F::seconds>(...)
        ::ppb::int64<F::seconds>,
        // ppb::on<F::nanos>(...)
        ::ppb::int32<F::nanos>>;
}

namespace ppb_gen::google::protobuf::Empty
{
    enum class F : ::std::int32_t
    {
    };

    constexpr ::std::size_t max_depth = 0;

    /*
     * google.protobuf.Empty declares no fields, so this schema registers only the
     * unknown-field catch-all; a ppb::schema must hold at least one descriptor.
     *
     * If you only need to know whether Empty was present, do not pay to
     * handle unknown fields here.  In the CONTAINING message, register
     * ppb::on<F::that_field>(...) to receive this submessage's raw span: that is
     * presence/absence detection without descending into it.  Handle unknown
     * fields here only when you must inspect the (otherwise unknown) contents.
     */
    using schema = ::ppb::auto_schema<
        // ppb::on_unknown<>(...)
        ::ppb::detect_unknown_fields<>>;

    using merge_schema = schema;
}

namespace ppb_gen::google::protobuf::FieldMask
{
    enum class F : ::std::int32_t
    {
        paths = 1,
    };

    constexpr ::std::size_t max_depth = 0;

    using schema = ::ppb::auto_schema<
        // ppb::on_each<F::paths>(...)
        ::ppb::unpacked_utf8string<F::paths>>;

    using merge_schema = schema;
}

namespace ppb_gen::google::protobuf::Timestamp
{
    enum class F : ::std::int32_t
    {
        seconds = 1,
        nanos = 2,
    };

    constexpr ::std::size_t max_depth = 0;

    using schema = ::ppb::auto_schema<
        // ppb::on<F::seconds>(...)
        ::ppb::proto3_int64<F::seconds>,
        // ppb::on<F::nanos>(...)
        ::ppb::proto3_int32<F::nanos>>;

    using merge_schema = ::ppb::auto_schema<
        // ppb::on<F::seconds>(...)
        ::ppb::int64<F::seconds>,
        // ppb::on<F::nanos>(...)
        ::ppb::int32<F::nanos>>;
}

namespace ppb_gen::google::protobuf::DoubleValue
{
    enum class F : ::std::int32_t
    {
        value = 1,
    };

    constexpr ::std::size_t max_depth = 0;

    using schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::proto3_f64<F::value>>;

    using merge_schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::f64<F::value>>;
}

namespace ppb_gen::google::protobuf::FloatValue
{
    enum class F : ::std::int32_t
    {
        value = 1,
    };

    constexpr ::std::size_t max_depth = 0;

    using schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::proto3_f32<F::value>>;

    using merge_schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::f32<F::value>>;
}

namespace ppb_gen::google::protobuf::Int64Value
{
    enum class F : ::std::int32_t
    {
        value = 1,
    };

    constexpr ::std::size_t max_depth = 0;

    using schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::proto3_int64<F::value>>;

    using merge_schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::int64<F::value>>;
}

namespace ppb_gen::google::protobuf::UInt64Value
{
    enum class F : ::std::int32_t
    {
        value = 1,
    };

    constexpr ::std::size_t max_depth = 0;

    using schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::proto3_uint64<F::value>>;

    using merge_schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::uint64<F::value>>;
}

namespace ppb_gen::google::protobuf::Int32Value
{
    enum class F : ::std::int32_t
    {
        value = 1,
    };

    constexpr ::std::size_t max_depth = 0;

    using schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::proto3_int32<F::value>>;

    using merge_schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::int32<F::value>>;
}

namespace ppb_gen::google::protobuf::UInt32Value
{
    enum class F : ::std::int32_t
    {
        value = 1,
    };

    constexpr ::std::size_t max_depth = 0;

    using schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::proto3_uint32<F::value>>;

    using merge_schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::uint32<F::value>>;
}

namespace ppb_gen::google::protobuf::BoolValue
{
    enum class F : ::std::int32_t
    {
        value = 1,
    };

    constexpr ::std::size_t max_depth = 0;

    using schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::proto3_boolean<F::value>>;

    using merge_schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::boolean<F::value>>;
}

namespace ppb_gen::google::protobuf::StringValue
{
    enum class F : ::std::int32_t
    {
        value = 1,
    };

    constexpr ::std::size_t max_depth = 0;

    using schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::proto3_utf8string<F::value>>;

    using merge_schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::utf8string<F::value>>;
}

namespace ppb_gen::google::protobuf::BytesValue
{
    enum class F : ::std::int32_t
    {
        value = 1,
    };

    constexpr ::std::size_t max_depth = 0;

    using schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::proto3_bytes<F::value>>;

    using merge_schema = ::ppb::auto_schema<
        // ppb::on<F::value>(...)
        ::ppb::bytes<F::value>>;
}

