ignore:
  - "tests/*"
  - "examples/*"

coverage:
  status:
    project:
      default:
        target: 89%
      directory_src:
        paths: ["src"]
        target: 99%
    patch:
      default:
        target:  100% # Minimum coverage for a PR
        threshold: 1% # wiggle room
        informational: true
